// This file is auto-generated by @hey-api/openapi-ts

export type AbsencePolicyResponse = {
    auto_notify_after_absences: number;
    cancellation_notice_hours: number;
    created_at: string;
    id: string;
    makeup_window_days: number;
    max_absences_per_term: number;
    studio_id: string;
    updated_at: string;
};

export type AbsencePolicyUpdateRequest = {
    auto_notify_after_absences?: (number | null);
    cancellation_notice_hours?: (number | null);
    makeup_window_days?: (number | null);
    max_absences_per_term?: (number | null);
};

export type AbsenceReportRequest = {
    makeup_requested?: boolean;
    reason?: (string | null);
};

export type AbsenceResponse = {
    created_at: string;
    id: string;
    makeup_occurrence_id?: (string | null);
    makeup_requested: boolean;
    occurrence_id: string;
    reason?: (string | null);
    reported_by: string;
    status: string;
    studio_id: string;
    updated_at: string;
};

/**
 * Single entry in a user's Account Access Log (read-only).
 */
export type AccountAccessLogEntry = {
    ended_at?: (string | null);
    impersonator_user_id: string;
    mode: 'silent' | 'live';
    playback_count?: number;
    reason: string;
    session_id: string;
    started_at: string;
};

export type mode = 'silent' | 'live';

export type AcknowledgementResponse = {
    acknowledged_at?: (string | null);
    assignment_id: string;
    created_at: string;
    id: string;
    recording_id?: (string | null);
    status: string;
};

export type ActivityLogResponse = {
    action: string;
    created_at: string;
    details?: (unknown | null);
    entity_id?: (string | null);
    entity_type: string;
    id: string;
    user_id: string;
};

export type AssignmentCreateRequest = {
    description?: (string | null);
    due_date: string;
    pieces?: (Array<(string)> | null);
    student_id: string;
    studio_id: string;
    techniques?: (Array<(string)> | null);
    title: string;
};

export type AssignmentFeedbackRequest = {
    feedback_rating: number;
    feedback_text: string;
};

export type AssignmentResponse = {
    created_at: string;
    description?: (string | null);
    due_date: string;
    feedback_rating?: (number | null);
    feedback_text?: (string | null);
    id: string;
    pieces?: (Array<(string)> | null);
    status: string;
    student_id: string;
    studio_id: string;
    teacher_id: string;
    techniques?: (Array<(string)> | null);
    title: string;
    updated_at: string;
};

export type AssignmentSummary = {
    created_at: string;
    due_date?: (string | null);
    id: string;
    status: string;
    title: string;
};

export type AttendanceMarkRequest = {
    attendance_status: string;
};

export type BetaFeedbackCreateRequest = {
    body: string;
    category?: 'bug' | 'feature_request' | 'usability' | 'performance' | 'other';
    severity?: 'critical' | 'high' | 'medium' | 'low';
};

export type category = 'bug' | 'feature_request' | 'usability' | 'performance' | 'other';

export type severity = 'critical' | 'high' | 'medium' | 'low';

export type BetaFeedbackResolveRequest = {
    [key: string]: unknown;
};

export type BetaFeedbackResponse = {
    body: string;
    category: 'bug' | 'feature_request' | 'usability' | 'performance' | 'other';
    created_at: string;
    id: string;
    resolved_at: (string | null);
    severity: 'critical' | 'high' | 'medium' | 'low';
    studio_id: string;
    submitted_at: string;
    submitted_by: string;
    updated_at: string;
};

export type BetaLandingTokenCreateRequest = {
    description?: (string | null);
};

export type BetaLandingTokenResponse = {
    created_at: string;
    created_by: string;
    description: (string | null);
    id: string;
    is_active: boolean;
    token: string;
};

export type BetaLandingValidateRequest = {
    token: string;
};

export type CategoryPreferenceResponse = {
    category: string;
    channel: string;
    enabled: boolean;
    id: string;
    updated_at: string;
    user_id: string;
};

export type CategoryPreferenceUpsertRequest = {
    category: string;
    channel: string;
    enabled: boolean;
};

export type ChildPaymentItem = {
    amount: string;
    created_at: string;
    currency: string;
    id: string;
    memo?: (string | null);
    method?: (string | null);
    status: string;
};

export type ChildPaymentsResponse = {
    child_user_id: string;
    payments?: Array<ChildPaymentItem>;
    studio_id: string;
    total_paid?: string;
    total_pending?: string;
    total_refunded?: string;
};

export type ChildPermissions = {
    can_communicate_with_teacher: boolean;
    can_manage_payments: boolean;
    can_view_progress: boolean;
    is_primary_contact: boolean;
};

export type ChildProgressResponse = {
    child_user_id: string;
    completed_assignments?: number;
    current_streak?: number;
    is_active?: boolean;
    longest_streak?: number;
    recent_recordings?: Array<ChildRecordingItem>;
    total_assignments?: number;
    total_practice_days?: number;
    weekly_minutes?: number;
};

export type ChildRecordingItem = {
    assignment_id?: (string | null);
    created_at: string;
    duration_seconds: number;
    id: string;
    uploaded_at?: (string | null);
};

export type ChildScheduleItem = {
    duration_minutes?: (number | null);
    end_time?: (string | null);
    lesson_id: string;
    occurrence_id?: (string | null);
    start_date: string;
    start_time?: (string | null);
    status?: (string | null);
    teacher_email?: (string | null);
};

export type ChildSummary = {
    child_user_id: string;
    current_streak?: number;
    email?: (string | null);
    latest_assignment_title?: (string | null);
    next_lesson_date?: (string | null);
    parent_child_id: string;
    permissions: ChildPermissions;
    studio_id: string;
    studio_name: string;
};

export type ConversationCreateRequest = {
    participant_ids: Array<(string)>;
    studio_id: string;
};

export type ConversationResponse = {
    created_at: string;
    created_by: string;
    id: string;
    studio_id: string;
    updated_at: string;
};

export type ConversionEligibilityResponse = {
    conversions: Array<ConversionOption>;
    current: 'minor' | 'teen' | 'adult';
};

export type current = 'minor' | 'teen' | 'adult';

export type ConversionOption = {
    message: string;
    requires_new_credentials: boolean;
    requires_parent_consent: boolean;
    target: 'minor' | 'teen' | 'adult';
};

export type target = 'minor' | 'teen' | 'adult';

export type ConvertRequest = {
    new_email?: (string | null);
    parent_consent_given?: boolean;
    target_age_class: 'minor' | 'teen' | 'adult';
};

export type target_age_class = 'minor' | 'teen' | 'adult';

export type ConvertResponse = {
    child_user_id: string;
    message: string;
    new_age_class: 'minor' | 'teen' | 'adult';
    parent_access_removed: boolean;
    previous_age_class: 'minor' | 'teen' | 'adult';
    studio_id: string;
};

export type new_age_class = 'minor' | 'teen' | 'adult';

export type previous_age_class = 'minor' | 'teen' | 'adult';

export type CoppaConsentResponse = {
    child_id: string;
    created_at: string;
    form_url: (string | null);
    id: string;
    parent_id: string;
    revocation_auto_delete_at: (string | null);
    revoked_at: (string | null);
    status: 'pending' | 'verified' | 'revoked' | 'expired';
    stripe_setup_intent_id: (string | null);
    studio_id: string;
    updated_at: string;
    verified_at: (string | null);
};

export type status = 'pending' | 'verified' | 'revoked' | 'expired';

export type CoppaInitiateRequest = {
    child_id: string;
    studio_id: string;
};

export type CoppaInitiateResponse = {
    client_secret: string;
    consent_id: string;
    status: 'pending' | 'verified' | 'revoked' | 'expired';
};

export type CoppaRevokeRequest = {
    consent_id: string;
};

export type CoppaSignedFormRequest = {
    consent_id: string;
    form_url: string;
};

export type CoppaWebhookResponse = {
    received: boolean;
};

export type DeletionConfirmRequest = {
    confirmation_token: string;
    request_id: string;
};

export type DeletionInitiateRequest = {
    child_id: string;
    studio_id: string;
};

export type DeletionResponse = {
    cancelled_at?: (string | null);
    child_id: string;
    completed_at?: (string | null);
    created_at: string;
    email_confirmed_at?: (string | null);
    id: string;
    parent_id: string;
    scheduled_delete_at?: (string | null);
    status: string;
    studio_id: string;
    t1_reminder_sent_at?: (string | null);
    t7_reminder_sent_at?: (string | null);
    updated_at: string;
};

export type DeviceRegisterRequest = {
    channel: 'expo' | 'webpush';
    keys?: ({
    [key: string]: (string);
} | null);
    token: string;
    user_agent?: (string | null);
};

export type channel = 'expo' | 'webpush';

export type DeviceResponse = {
    channel: string;
    created_at: string;
    id: string;
    keys?: ({
    [key: string]: (string);
} | null);
    last_used_at?: (string | null);
    token: string;
    user_agent?: (string | null);
    user_id: string;
};

export type EmployeeCreateRequest = {
    notes?: (string | null);
    role: 'owner' | 'support' | 'verifier';
    user_id: string;
};

export type role = 'owner' | 'support' | 'verifier';

export type EmployeeResponse = {
    created_at: string;
    created_by?: (string | null);
    id: string;
    notes?: (string | null);
    role: 'owner' | 'support' | 'verifier';
    user_id: string;
};

export type EmployeeUpdateRequest = {
    notes?: (string | null);
    role?: ('owner' | 'support' | 'verifier' | null);
};

export type HealthResponse = {
    git_sha: string;
    status: string;
    version: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ImpersonationSessionResponse = {
    ended_at?: (string | null);
    id: string;
    impersonator_user_id: string;
    ip_address?: (string | null);
    mode: 'silent' | 'live';
    notification_sent_at?: (string | null);
    reason: string;
    started_at: string;
    studio_id?: (string | null);
    target_user_id: string;
    user_agent?: (string | null);
};

export type ImpersonationStartRequest = {
    mode?: 'silent' | 'live';
    reason: string;
};

export type InvitationBatchCreateRequest = {
    child_names: Array<(string)>;
    invited_email: string;
};

export type InvitationCreateRequest = {
    age_class?: ('minor' | 'teen' | 'adult' | null);
    invited_email: string;
    persona: 'studio-owner' | 'teacher' | 'parent' | 'student';
};

export type persona = 'studio-owner' | 'teacher' | 'parent' | 'student';

export type InvitationRedeemRequest = {
    token: string;
};

export type InvitationRedeemResponse = {
    invitation_id: string;
    persona: 'studio-owner' | 'teacher' | 'parent' | 'student';
    status: 'pending' | 'accepted' | 'declined' | 'expired' | 'revoked';
    studio_id: string;
};

export type status2 = 'pending' | 'accepted' | 'declined' | 'expired' | 'revoked';

export type InvitationResponse = {
    age_class: ('minor' | 'teen' | 'adult' | null);
    auto_approve: boolean;
    created_at: string;
    expires_at: string;
    id: string;
    invited_by: string;
    invited_email: string;
    invited_user_id: (string | null);
    persona: 'studio-owner' | 'teacher' | 'parent' | 'student';
    redeemed_at: (string | null);
    redeemed_by: (string | null);
    status: 'pending' | 'accepted' | 'declined' | 'expired' | 'revoked';
    studio_id: string;
    updated_at: string;
};

export type LessonCreateRequest = {
    cadence?: string;
    cost?: (number | null);
    day_of_week?: (number | null);
    description?: (string | null);
    duration_minutes: number;
    end_date?: (string | null);
    is_recurring?: boolean;
    is_trial?: boolean;
    start_date: string;
    start_time: string;
    student_id: string;
    studio_id: string;
    title: string;
};

export type LessonResponse = {
    cadence: string;
    cost?: (number | null);
    created_at: string;
    created_by: string;
    day_of_week?: (number | null);
    description?: (string | null);
    duration_minutes: number;
    end_date?: (string | null);
    id: string;
    is_paid: boolean;
    is_recurring: boolean;
    is_trial: boolean;
    start_date: string;
    start_time: string;
    student_id: string;
    studio_id: string;
    teacher_id: string;
    title: string;
    updated_at: string;
};

export type LessonUpdateRequest = {
    cost?: (number | null);
    description?: (string | null);
    duration_minutes?: (number | null);
    end_date?: (string | null);
    is_trial?: (boolean | null);
    start_time?: (string | null);
    title?: (string | null);
};

export type LoanCreateRequest = {
    description?: (string | null);
    item_name: string;
    loaned_at?: (string | null);
    student_user_id: string;
    studio_id: string;
};

export type LoanResponse = {
    created_at: string;
    created_by: string;
    description?: (string | null);
    id: string;
    item_name: string;
    loaned_at: string;
    returned_at?: (string | null);
    student_user_id: string;
    studio_id: string;
    updated_at: string;
};

export type LoanUpdateRequest = {
    description?: (string | null);
    item_name?: (string | null);
    returned_at?: (string | null);
};

export type MessageCreateRequest = {
    body: string;
};

export type MessageResponse = {
    body: string;
    conversation_id: string;
    created_at: string;
    id: string;
    sender_id: string;
};

export type NotificationTemplateResponse = {
    body_template: string;
    category: string;
    channels: Array<(string)>;
    created_at: string;
    enabled: boolean;
    event_type: string;
    id: string;
    persona: string;
    title_template: string;
    trigger_source: string;
    updated_at: string;
};

export type OccurrenceNotesRequest = {
    improvement_areas?: (string | null);
    next_focus?: (string | null);
    progress_notes?: (string | null);
    strengths?: (string | null);
    teacher_notes?: (string | null);
};

export type OccurrenceResponse = {
    attendance_status: string;
    cost?: (number | null);
    created_at: string;
    duration_minutes: number;
    id: string;
    improvement_areas?: (string | null);
    is_makeup: boolean;
    is_paid: boolean;
    lesson_id: string;
    makeup_for_id?: (string | null);
    marked_at?: (string | null);
    marked_by?: (string | null);
    next_focus?: (string | null);
    occurrence_date: string;
    progress_notes?: (string | null);
    start_time: string;
    strengths?: (string | null);
    studio_id: string;
    teacher_notes?: (string | null);
    updated_at: string;
};

export type OutstandingBalanceResponse = {
    student_user_id: string;
    studio_id: string;
    total_paid: string;
    total_pending: string;
    total_refunded: string;
};

export type ParentChildPermissions = {
    can_communicate_with_teacher: boolean;
    can_manage_payments: boolean;
    can_view_progress: boolean;
    child_user_id: string;
    created_at: string;
    id: string;
    is_primary_contact: boolean;
    parent_id: string;
    parent_user_id: string;
};

export type ParentChildPermissionUpdate = {
    can_communicate_with_teacher?: (boolean | null);
    can_manage_payments?: (boolean | null);
    can_view_progress?: (boolean | null);
    is_primary_contact?: (boolean | null);
};

export type ParentDashboardResponse = {
    children: Array<ChildSummary>;
};

export type ParentInfo = {
    children?: Array<ParentChildPermissions>;
    parent_id: string;
    user_id: string;
};

export type PaymentCreateRequest = {
    amount: (number | string);
    currency?: string;
    memo?: (string | null);
    method?: (string | null);
    payer_user_id?: (string | null);
    student_user_id: string;
};

export type PaymentResponse = {
    amount: string;
    created_at: string;
    created_by: string;
    currency: string;
    id: string;
    memo?: (string | null);
    method?: (string | null);
    payer_user_id?: (string | null);
    refunded_at?: (string | null);
    status: string;
    student_user_id: string;
    studio_id: string;
    updated_at: string;
};

export type PaymentUpdateRequest = {
    amount?: (number | string | null);
    memo?: (string | null);
    method?: (string | null);
    status?: ('pending' | 'paid' | 'refunded' | null);
};

export type PlaybackUrlResponse = {
    expires_in_seconds?: number;
    playback_url: string;
    recording_id: string;
};

export type PreferencesResponse = {
    expo_push_enabled?: boolean;
    quiet_hours_end?: (string | null);
    quiet_hours_start?: (string | null);
    realtime_enabled?: boolean;
    updated_at?: (string | null);
    user_id: string;
    web_push_enabled?: boolean;
};

export type PreferencesUpdateRequest = {
    expo_push_enabled?: (boolean | null);
    quiet_hours_end?: (string | null);
    quiet_hours_start?: (string | null);
    realtime_enabled?: (boolean | null);
    web_push_enabled?: (boolean | null);
};

export type RecordingCreateRequest = {
    assignment_id?: (string | null);
    duration_seconds: number;
    file_size_bytes?: (number | null);
    mime_type: string;
    studio_id: string;
};

export type RecordingHistoryItem = {
    assignment_id?: (string | null);
    created_at: string;
    duration_seconds: number;
    id: string;
    uploaded_at?: (string | null);
};

export type RecordingResponse = {
    assignment_id?: (string | null);
    created_at: string;
    deleted_at?: (string | null);
    duration_seconds: number;
    file_size_bytes?: (number | null);
    id: string;
    mime_type: string;
    r2_object_key: string;
    student_id: string;
    studio_id: string;
    updated_at: string;
    uploaded_at?: (string | null);
};

export type ResourceCreateRequest = {
    category?: (string | null);
    description?: (string | null);
    studio_id: string;
    title: string;
    url: string;
};

export type ResourceResponse = {
    category?: (string | null);
    created_at: string;
    created_by?: (string | null);
    description?: (string | null);
    id: string;
    studio_id: string;
    title: string;
    updated_at: string;
    url: string;
};

export type ResourceUpdateRequest = {
    category?: (string | null);
    description?: (string | null);
    title?: (string | null);
    url?: (string | null);
};

export type SettingCreateRequest = {
    category: 'rate_limits' | 'business_rule_caps' | 'notification_delays' | 'coppa_grace_windows';
    description?: (string | null);
    key: string;
    value_json: unknown;
};

export type category2 = 'rate_limits' | 'business_rule_caps' | 'notification_delays' | 'coppa_grace_windows';

export type SettingResponse = {
    category: 'rate_limits' | 'business_rule_caps' | 'notification_delays' | 'coppa_grace_windows';
    description?: (string | null);
    id: string;
    key: string;
    updated_at: string;
    updated_by?: (string | null);
    value_json: unknown;
};

export type SettingUpdateRequest = {
    description?: (string | null);
    value_json: unknown;
};

export type StreakResponse = {
    current_streak: number;
    is_active: boolean;
    longest_streak: number;
    total_practice_days: number;
    weekly_minutes: number;
};

export type StudentDashboardResponse = {
    recent_recordings: Array<RecordingHistoryItem>;
    streak: StreakResponse;
    upcoming_assignments: Array<AssignmentSummary>;
};

export type StudentDetail = {
    email?: (string | null);
    joined_at: string;
    loans?: Array<LoanResponse>;
    parents?: Array<ParentInfo>;
    role: string;
    user_id: string;
};

export type StudentListItem = {
    email?: (string | null);
    joined_at: string;
    role: string;
    user_id: string;
};

export type StudioCreateRequest = {
    display_name?: (string | null);
    name: string;
    timezone?: string;
};

export type StudioResponse = {
    beta_cohort: boolean;
    created_at: string;
    display_name?: (string | null);
    id: string;
    logo_url?: (string | null);
    name: string;
    primary_color?: (string | null);
    state: string;
    timezone: string;
    updated_at: string;
};

export type StudioUpdateRequest = {
    display_name?: (string | null);
    logo_url?: (string | null);
    primary_color?: (string | null);
    timezone?: (string | null);
};

export type UploadConfirmRequest = {
    file_size_bytes?: (number | null);
};

export type UploadUrlResponse = {
    r2_object_key: string;
    recording_id: string;
    upload_url: string;
};

export type ValidationError = {
    ctx?: {
        [key: string]: unknown;
    };
    input?: unknown;
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type WaitlistBypassCreateRequest = {
    email: string;
    name: string;
    studio_name?: (string | null);
};

export type WaitlistEntryResponse = {
    bypass_token: (string | null);
    created_at: string;
    email: string;
    id: string;
    ip_address: (string | null);
    name: string;
    rejection_reason: (string | null);
    reviewed_at: (string | null);
    reviewed_by: (string | null);
    status: 'pending' | 'approved' | 'rejected' | 'invited';
    studio_id: (string | null);
    studio_name: (string | null);
    updated_at: string;
};

export type status3 = 'pending' | 'approved' | 'rejected' | 'invited';

export type WaitlistMessageRequest = {
    body: string;
};

export type WaitlistMessageResponse = {
    body: string;
    created_at: string;
    id: string;
    sender_id: string;
    waitlist_entry_id: string;
};

export type WaitlistRejectRequest = {
    reason?: (string | null);
};

export type WaitlistSubmitRequest = {
    captcha_token?: (string | null);
    email: string;
    name: string;
    studio_name?: (string | null);
};

export type WaitlistSubmitResponse = {
    created_at: string;
    email: string;
    id: string;
    name: string;
    status: 'pending' | 'approved' | 'rejected' | 'invited';
    studio_name: (string | null);
    updated_at: string;
};