// This file is auto-generated by @hey-api/openapi-ts

export type DeviceRegisterRequest = {
    channel: 'expo' | 'webpush';
    keys?: ({
    [key: string]: (string);
} | null);
    token: string;
    user_agent?: (string | null);
};

export type channel = 'expo' | 'webpush';

export type DeviceResponse = {
    channel: string;
    created_at: string;
    id: string;
    keys?: ({
    [key: string]: (string);
} | null);
    last_used_at?: (string | null);
    token: string;
    user_agent?: (string | null);
    user_id: string;
};

export type HealthResponse = {
    git_sha: string;
    status: string;
    version: string;
};

export type PreferencesResponse = {
    expo_push_enabled?: boolean;
    quiet_hours_end?: (string | null);
    quiet_hours_start?: (string | null);
    realtime_enabled?: boolean;
    updated_at?: (string | null);
    user_id: string;
    web_push_enabled?: boolean;
};

export type PreferencesUpdateRequest = {
    expo_push_enabled?: (boolean | null);
    quiet_hours_end?: (string | null);
    quiet_hours_start?: (string | null);
    realtime_enabled?: (boolean | null);
    web_push_enabled?: (boolean | null);
};

export type StudioCreateRequest = {
    display_name?: (string | null);
    name: string;
    timezone?: string;
};

export type StudioResponse = {
    beta_cohort: boolean;
    created_at: string;
    display_name?: (string | null);
    id: string;
    logo_url?: (string | null);
    name: string;
    primary_color?: (string | null);
    state: string;
    timezone: string;
    updated_at: string;
};

export type StudioUpdateRequest = {
    display_name?: (string | null);
    logo_url?: (string | null);
    primary_color?: (string | null);
    timezone?: (string | null);
};