// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.snapshot.json` | (string & {});
};

/**
 * AcknowledgementResponse
 */
export type AcknowledgementResponse = {
    /**
     * Acknowledged At
     */
    acknowledged_at?: string | null;
    /**
     * Assignment Id
     */
    assignment_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Id
     */
    id: string;
    /**
     * Recording Id
     */
    recording_id?: string | null;
    /**
     * Status
     */
    status: string;
};

/**
 * ActivityLogResponse
 */
export type ActivityLogResponse = {
    /**
     * Action
     */
    action: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Details
     */
    details?: unknown | null;
    /**
     * Entity Id
     */
    entity_id?: string | null;
    /**
     * Entity Type
     */
    entity_type: string;
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
};

/**
 * AssignmentCreateRequest
 */
export type AssignmentCreateRequest = {
    /**
     * Description
     */
    description?: string | null;
    /**
     * Due Date
     */
    due_date: string;
    /**
     * Pieces
     */
    pieces?: Array<string> | null;
    /**
     * Student Id
     */
    student_id: string;
    /**
     * Studio Id
     */
    studio_id: string;
    /**
     * Techniques
     */
    techniques?: Array<string> | null;
    /**
     * Title
     */
    title: string;
};

/**
 * AssignmentFeedbackRequest
 */
export type AssignmentFeedbackRequest = {
    /**
     * Feedback Rating
     */
    feedback_rating: number;
    /**
     * Feedback Text
     */
    feedback_text: string;
};

/**
 * AssignmentResponse
 */
export type AssignmentResponse = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Due Date
     */
    due_date: string;
    /**
     * Feedback Rating
     */
    feedback_rating?: number | null;
    /**
     * Feedback Text
     */
    feedback_text?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Pieces
     */
    pieces?: Array<string> | null;
    /**
     * Status
     */
    status: string;
    /**
     * Student Id
     */
    student_id: string;
    /**
     * Studio Id
     */
    studio_id: string;
    /**
     * Teacher Id
     */
    teacher_id: string;
    /**
     * Techniques
     */
    techniques?: Array<string> | null;
    /**
     * Title
     */
    title: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * CategoryPreferenceResponse
 */
export type CategoryPreferenceResponse = {
    /**
     * Category
     */
    category: string;
    /**
     * Channel
     */
    channel: string;
    /**
     * Enabled
     */
    enabled: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * User Id
     */
    user_id: string;
};

/**
 * CategoryPreferenceUpsertRequest
 */
export type CategoryPreferenceUpsertRequest = {
    /**
     * Category
     */
    category: string;
    /**
     * Channel
     */
    channel: string;
    /**
     * Enabled
     */
    enabled: boolean;
};

/**
 * ConversationCreateRequest
 */
export type ConversationCreateRequest = {
    /**
     * Participant Ids
     */
    participant_ids: Array<string>;
    /**
     * Studio Id
     */
    studio_id: string;
};

/**
 * ConversationResponse
 */
export type ConversationResponse = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Created By
     */
    created_by: string;
    /**
     * Id
     */
    id: string;
    /**
     * Studio Id
     */
    studio_id: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * DeviceRegisterRequest
 */
export type DeviceRegisterRequest = {
    /**
     * Channel
     */
    channel: 'expo' | 'webpush';
    /**
     * Keys
     */
    keys?: {
        [key: string]: string;
    } | null;
    /**
     * Token
     */
    token: string;
    /**
     * User Agent
     */
    user_agent?: string | null;
};

/**
 * DeviceResponse
 */
export type DeviceResponse = {
    /**
     * Channel
     */
    channel: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Id
     */
    id: string;
    /**
     * Keys
     */
    keys?: {
        [key: string]: string;
    } | null;
    /**
     * Last Used At
     */
    last_used_at?: string | null;
    /**
     * Token
     */
    token: string;
    /**
     * User Agent
     */
    user_agent?: string | null;
    /**
     * User Id
     */
    user_id: string;
};

/**
 * EmployeeCreateRequest
 */
export type EmployeeCreateRequest = {
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Role
     */
    role: 'owner' | 'support' | 'verifier';
    /**
     * User Id
     */
    user_id: string;
};

/**
 * EmployeeResponse
 */
export type EmployeeResponse = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Created By
     */
    created_by?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Role
     */
    role: 'owner' | 'support' | 'verifier';
    /**
     * User Id
     */
    user_id: string;
};

/**
 * EmployeeUpdateRequest
 */
export type EmployeeUpdateRequest = {
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Role
     */
    role?: 'owner' | 'support' | 'verifier' | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthResponse
 */
export type HealthResponse = {
    /**
     * Git Sha
     */
    git_sha: string;
    /**
     * Status
     */
    status: string;
    /**
     * Version
     */
    version: string;
};

/**
 * InvitationBatchCreateRequest
 */
export type InvitationBatchCreateRequest = {
    /**
     * Child Names
     */
    child_names: Array<string>;
    /**
     * Invited Email
     */
    invited_email: string;
};

/**
 * InvitationCreateRequest
 */
export type InvitationCreateRequest = {
    /**
     * Age Class
     */
    age_class?: 'minor' | 'teen' | 'adult' | null;
    /**
     * Invited Email
     */
    invited_email: string;
    /**
     * Persona
     */
    persona: 'studio-owner' | 'teacher' | 'parent' | 'student';
};

/**
 * InvitationRedeemRequest
 */
export type InvitationRedeemRequest = {
    /**
     * Token
     */
    token: string;
};

/**
 * InvitationRedeemResponse
 */
export type InvitationRedeemResponse = {
    /**
     * Invitation Id
     */
    invitation_id: string;
    /**
     * Persona
     */
    persona: 'studio-owner' | 'teacher' | 'parent' | 'student';
    /**
     * Status
     */
    status: 'pending' | 'accepted' | 'declined' | 'expired' | 'revoked';
    /**
     * Studio Id
     */
    studio_id: string;
};

/**
 * InvitationResponse
 */
export type InvitationResponse = {
    /**
     * Age Class
     */
    age_class: 'minor' | 'teen' | 'adult' | null;
    /**
     * Auto Approve
     */
    auto_approve: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Expires At
     */
    expires_at: string;
    /**
     * Id
     */
    id: string;
    /**
     * Invited By
     */
    invited_by: string;
    /**
     * Invited Email
     */
    invited_email: string;
    /**
     * Invited User Id
     */
    invited_user_id: string | null;
    /**
     * Persona
     */
    persona: 'studio-owner' | 'teacher' | 'parent' | 'student';
    /**
     * Redeemed At
     */
    redeemed_at: string | null;
    /**
     * Redeemed By
     */
    redeemed_by: string | null;
    /**
     * Status
     */
    status: 'pending' | 'accepted' | 'declined' | 'expired' | 'revoked';
    /**
     * Studio Id
     */
    studio_id: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * LoanCreateRequest
 */
export type LoanCreateRequest = {
    /**
     * Description
     */
    description?: string | null;
    /**
     * Item Name
     */
    item_name: string;
    /**
     * Loaned At
     */
    loaned_at?: string | null;
    /**
     * Student User Id
     */
    student_user_id: string;
    /**
     * Studio Id
     */
    studio_id: string;
};

/**
 * LoanResponse
 */
export type LoanResponse = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Created By
     */
    created_by: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Item Name
     */
    item_name: string;
    /**
     * Loaned At
     */
    loaned_at: string;
    /**
     * Returned At
     */
    returned_at?: string | null;
    /**
     * Student User Id
     */
    student_user_id: string;
    /**
     * Studio Id
     */
    studio_id: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * LoanUpdateRequest
 */
export type LoanUpdateRequest = {
    /**
     * Description
     */
    description?: string | null;
    /**
     * Item Name
     */
    item_name?: string | null;
    /**
     * Returned At
     */
    returned_at?: string | null;
};

/**
 * MessageCreateRequest
 */
export type MessageCreateRequest = {
    /**
     * Body
     */
    body: string;
};

/**
 * MessageResponse
 */
export type MessageResponse = {
    /**
     * Body
     */
    body: string;
    /**
     * Conversation Id
     */
    conversation_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Id
     */
    id: string;
    /**
     * Sender Id
     */
    sender_id: string;
};

/**
 * NotificationTemplateResponse
 */
export type NotificationTemplateResponse = {
    /**
     * Body Template
     */
    body_template: string;
    /**
     * Category
     */
    category: string;
    /**
     * Channels
     */
    channels: Array<string>;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Enabled
     */
    enabled: boolean;
    /**
     * Event Type
     */
    event_type: string;
    /**
     * Id
     */
    id: string;
    /**
     * Persona
     */
    persona: string;
    /**
     * Title Template
     */
    title_template: string;
    /**
     * Trigger Source
     */
    trigger_source: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ParentChildPermissionUpdate
 */
export type ParentChildPermissionUpdate = {
    /**
     * Can Communicate With Teacher
     */
    can_communicate_with_teacher?: boolean | null;
    /**
     * Can Manage Payments
     */
    can_manage_payments?: boolean | null;
    /**
     * Can View Progress
     */
    can_view_progress?: boolean | null;
    /**
     * Is Primary Contact
     */
    is_primary_contact?: boolean | null;
};

/**
 * ParentChildPermissions
 */
export type ParentChildPermissions = {
    /**
     * Can Communicate With Teacher
     */
    can_communicate_with_teacher: boolean;
    /**
     * Can Manage Payments
     */
    can_manage_payments: boolean;
    /**
     * Can View Progress
     */
    can_view_progress: boolean;
    /**
     * Child User Id
     */
    child_user_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Id
     */
    id: string;
    /**
     * Is Primary Contact
     */
    is_primary_contact: boolean;
    /**
     * Parent Id
     */
    parent_id: string;
    /**
     * Parent User Id
     */
    parent_user_id: string;
};

/**
 * ParentInfo
 */
export type ParentInfo = {
    /**
     * Children
     */
    children?: Array<ParentChildPermissions>;
    /**
     * Parent Id
     */
    parent_id: string;
    /**
     * User Id
     */
    user_id: string;
};

/**
 * PlaybackUrlResponse
 */
export type PlaybackUrlResponse = {
    /**
     * Expires In Seconds
     */
    expires_in_seconds?: number;
    /**
     * Playback Url
     */
    playback_url: string;
    /**
     * Recording Id
     */
    recording_id: string;
};

/**
 * PreferencesResponse
 */
export type PreferencesResponse = {
    /**
     * Expo Push Enabled
     */
    expo_push_enabled?: boolean;
    /**
     * Quiet Hours End
     */
    quiet_hours_end?: string | null;
    /**
     * Quiet Hours Start
     */
    quiet_hours_start?: string | null;
    /**
     * Realtime Enabled
     */
    realtime_enabled?: boolean;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Web Push Enabled
     */
    web_push_enabled?: boolean;
};

/**
 * PreferencesUpdateRequest
 */
export type PreferencesUpdateRequest = {
    /**
     * Expo Push Enabled
     */
    expo_push_enabled?: boolean | null;
    /**
     * Quiet Hours End
     */
    quiet_hours_end?: string | null;
    /**
     * Quiet Hours Start
     */
    quiet_hours_start?: string | null;
    /**
     * Realtime Enabled
     */
    realtime_enabled?: boolean | null;
    /**
     * Web Push Enabled
     */
    web_push_enabled?: boolean | null;
};

/**
 * RecordingCreateRequest
 */
export type RecordingCreateRequest = {
    /**
     * Assignment Id
     */
    assignment_id?: string | null;
    /**
     * Duration Seconds
     */
    duration_seconds: number;
    /**
     * File Size Bytes
     */
    file_size_bytes?: number | null;
    /**
     * Mime Type
     */
    mime_type: string;
    /**
     * Studio Id
     */
    studio_id: string;
};

/**
 * RecordingResponse
 */
export type RecordingResponse = {
    /**
     * Assignment Id
     */
    assignment_id?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Deleted At
     */
    deleted_at?: string | null;
    /**
     * Duration Seconds
     */
    duration_seconds: number;
    /**
     * File Size Bytes
     */
    file_size_bytes?: number | null;
    /**
     * Id
     */
    id: string;
    /**
     * Mime Type
     */
    mime_type: string;
    /**
     * R2 Object Key
     */
    r2_object_key: string;
    /**
     * Student Id
     */
    student_id: string;
    /**
     * Studio Id
     */
    studio_id: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Uploaded At
     */
    uploaded_at?: string | null;
};

/**
 * ResourceCreateRequest
 */
export type ResourceCreateRequest = {
    /**
     * Category
     */
    category?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Studio Id
     */
    studio_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Url
     */
    url: string;
};

/**
 * ResourceResponse
 */
export type ResourceResponse = {
    /**
     * Category
     */
    category?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Created By
     */
    created_by?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Studio Id
     */
    studio_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Url
     */
    url: string;
};

/**
 * ResourceUpdateRequest
 */
export type ResourceUpdateRequest = {
    /**
     * Category
     */
    category?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Url
     */
    url?: string | null;
};

/**
 * SettingCreateRequest
 */
export type SettingCreateRequest = {
    /**
     * Category
     */
    category: 'rate_limits' | 'business_rule_caps' | 'notification_delays' | 'coppa_grace_windows';
    /**
     * Description
     */
    description?: string | null;
    /**
     * Key
     */
    key: string;
    /**
     * Value Json
     */
    value_json: unknown;
};

/**
 * SettingResponse
 */
export type SettingResponse = {
    /**
     * Category
     */
    category: 'rate_limits' | 'business_rule_caps' | 'notification_delays' | 'coppa_grace_windows';
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Key
     */
    key: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Updated By
     */
    updated_by?: string | null;
    /**
     * Value Json
     */
    value_json: unknown;
};

/**
 * SettingUpdateRequest
 */
export type SettingUpdateRequest = {
    /**
     * Description
     */
    description?: string | null;
    /**
     * Value Json
     */
    value_json: unknown;
};

/**
 * StudentDetail
 */
export type StudentDetail = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Joined At
     */
    joined_at: string;
    /**
     * Loans
     */
    loans?: Array<LoanResponse>;
    /**
     * Parents
     */
    parents?: Array<ParentInfo>;
    /**
     * Role
     */
    role: string;
    /**
     * User Id
     */
    user_id: string;
};

/**
 * StudentListItem
 */
export type StudentListItem = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Joined At
     */
    joined_at: string;
    /**
     * Role
     */
    role: string;
    /**
     * User Id
     */
    user_id: string;
};

/**
 * StudioCreateRequest
 */
export type StudioCreateRequest = {
    /**
     * Display Name
     */
    display_name?: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Timezone
     */
    timezone?: string;
};

/**
 * StudioResponse
 */
export type StudioResponse = {
    /**
     * Beta Cohort
     */
    beta_cohort: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Display Name
     */
    display_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Logo Url
     */
    logo_url?: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Primary Color
     */
    primary_color?: string | null;
    /**
     * State
     */
    state: string;
    /**
     * Timezone
     */
    timezone: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * StudioUpdateRequest
 */
export type StudioUpdateRequest = {
    /**
     * Display Name
     */
    display_name?: string | null;
    /**
     * Logo Url
     */
    logo_url?: string | null;
    /**
     * Primary Color
     */
    primary_color?: string | null;
    /**
     * Timezone
     */
    timezone?: string | null;
};

/**
 * UploadConfirmRequest
 */
export type UploadConfirmRequest = {
    /**
     * File Size Bytes
     */
    file_size_bytes?: number | null;
};

/**
 * UploadUrlResponse
 */
export type UploadUrlResponse = {
    /**
     * R2 Object Key
     */
    r2_object_key: string;
    /**
     * Recording Id
     */
    recording_id: string;
    /**
     * Upload Url
     */
    upload_url: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * WaitlistBypassCreateRequest
 */
export type WaitlistBypassCreateRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name: string;
    /**
     * Studio Name
     */
    studio_name?: string | null;
};

/**
 * WaitlistEntryResponse
 */
export type WaitlistEntryResponse = {
    /**
     * Bypass Token
     */
    bypass_token: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Email
     */
    email: string;
    /**
     * Id
     */
    id: string;
    /**
     * Ip Address
     */
    ip_address: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Rejection Reason
     */
    rejection_reason: string | null;
    /**
     * Reviewed At
     */
    reviewed_at: string | null;
    /**
     * Reviewed By
     */
    reviewed_by: string | null;
    /**
     * Status
     */
    status: 'pending' | 'approved' | 'rejected' | 'invited';
    /**
     * Studio Id
     */
    studio_id: string | null;
    /**
     * Studio Name
     */
    studio_name: string | null;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * WaitlistMessageRequest
 */
export type WaitlistMessageRequest = {
    /**
     * Body
     */
    body: string;
};

/**
 * WaitlistMessageResponse
 */
export type WaitlistMessageResponse = {
    /**
     * Body
     */
    body: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Id
     */
    id: string;
    /**
     * Sender Id
     */
    sender_id: string;
    /**
     * Waitlist Entry Id
     */
    waitlist_entry_id: string;
};

/**
 * WaitlistRejectRequest
 */
export type WaitlistRejectRequest = {
    /**
     * Reason
     */
    reason?: string | null;
};

/**
 * WaitlistSubmitRequest
 */
export type WaitlistSubmitRequest = {
    /**
     * Captcha Token
     */
    captcha_token?: string | null;
    /**
     * Email
     */
    email: string;
    /**
     * Name
     */
    name: string;
    /**
     * Studio Name
     */
    studio_name?: string | null;
};

export type ListAllStudiosAdminStudiosGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/studios';
};

export type ListAllStudiosAdminStudiosGetErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Superadmin role required
     */
    403: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type ListAllStudiosAdminStudiosGetResponses = {
    /**
     * Response List All Studios Admin Studios Get
     *
     * Successful Response
     */
    200: Array<StudioResponse>;
};

export type ListAllStudiosAdminStudiosGetResponse = ListAllStudiosAdminStudiosGetResponses[keyof ListAllStudiosAdminStudiosGetResponses];

export type GetStudioAdminStudiosStudioIdGetData = {
    body?: never;
    path: {
        /**
         * Studio Id
         */
        studio_id: string;
    };
    query?: never;
    url: '/admin/studios/{studio_id}';
};

export type GetStudioAdminStudiosStudioIdGetErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Superadmin role required
     */
    403: unknown;
    /**
     * Studio not found
     */
    404: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type GetStudioAdminStudiosStudioIdGetResponses = {
    /**
     * Successful Response
     */
    200: StudioResponse;
};

export type GetStudioAdminStudiosStudioIdGetResponse = GetStudioAdminStudiosStudioIdGetResponses[keyof GetStudioAdminStudiosStudioIdGetResponses];

export type SuspendStudioAdminStudiosStudioIdSuspendPostData = {
    body?: never;
    path: {
        /**
         * Studio Id
         */
        studio_id: string;
    };
    query?: never;
    url: '/admin/studios/{studio_id}/suspend';
};

export type SuspendStudioAdminStudiosStudioIdSuspendPostErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Superadmin role required
     */
    403: unknown;
    /**
     * Studio not found
     */
    404: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type SuspendStudioAdminStudiosStudioIdSuspendPostResponses = {
    /**
     * Successful Response
     */
    200: StudioResponse;
};

export type SuspendStudioAdminStudiosStudioIdSuspendPostResponse = SuspendStudioAdminStudiosStudioIdSuspendPostResponses[keyof SuspendStudioAdminStudiosStudioIdSuspendPostResponses];

export type VerifyStudioAdminStudiosStudioIdVerifyPostData = {
    body?: never;
    path: {
        /**
         * Studio Id
         */
        studio_id: string;
    };
    query?: never;
    url: '/admin/studios/{studio_id}/verify';
};

export type VerifyStudioAdminStudiosStudioIdVerifyPostErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Superadmin role required
     */
    403: unknown;
    /**
     * Studio not found
     */
    404: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type VerifyStudioAdminStudiosStudioIdVerifyPostResponses = {
    /**
     * Successful Response
     */
    200: StudioResponse;
};

export type VerifyStudioAdminStudiosStudioIdVerifyPostResponse = VerifyStudioAdminStudiosStudioIdVerifyPostResponses[keyof VerifyStudioAdminStudiosStudioIdVerifyPostResponses];

export type ListPendingStudiosAdminVerificationQueueGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/verification-queue';
};

export type ListPendingStudiosAdminVerificationQueueGetErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Superadmin role required
     */
    403: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type ListPendingStudiosAdminVerificationQueueGetResponses = {
    /**
     * Response List Pending Studios Admin Verification Queue Get
     *
     * Successful Response
     */
    200: Array<StudioResponse>;
};

export type ListPendingStudiosAdminVerificationQueueGetResponse = ListPendingStudiosAdminVerificationQueueGetResponses[keyof ListPendingStudiosAdminVerificationQueueGetResponses];

export type ListWaitlistAdminWaitlistGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Status
         */
        status?: 'pending' | 'approved' | 'rejected' | 'invited' | null;
    };
    url: '/admin/waitlist';
};

export type ListWaitlistAdminWaitlistGetErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Superadmin role required
     */
    403: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type ListWaitlistAdminWaitlistGetResponses = {
    /**
     * Response List Waitlist Admin Waitlist Get
     *
     * Successful Response
     */
    200: Array<WaitlistEntryResponse>;
};

export type ListWaitlistAdminWaitlistGetResponse = ListWaitlistAdminWaitlistGetResponses[keyof ListWaitlistAdminWaitlistGetResponses];

export type CreateBypassInviteAdminWaitlistBypassPostData = {
    body: WaitlistBypassCreateRequest;
    path?: never;
    query?: never;
    url: '/admin/waitlist/bypass';
};

export type CreateBypassInviteAdminWaitlistBypassPostErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Superadmin role required
     */
    403: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type CreateBypassInviteAdminWaitlistBypassPostResponses = {
    /**
     * Successful Response
     */
    201: WaitlistEntryResponse;
};

export type CreateBypassInviteAdminWaitlistBypassPostResponse = CreateBypassInviteAdminWaitlistBypassPostResponses[keyof CreateBypassInviteAdminWaitlistBypassPostResponses];

export type GetWaitlistEntryAdminWaitlistEntryIdGetData = {
    body?: never;
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
    };
    query?: never;
    url: '/admin/waitlist/{entry_id}';
};

export type GetWaitlistEntryAdminWaitlistEntryIdGetErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Superadmin role required
     */
    403: unknown;
    /**
     * Entry not found
     */
    404: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type GetWaitlistEntryAdminWaitlistEntryIdGetResponses = {
    /**
     * Successful Response
     */
    200: WaitlistEntryResponse;
};

export type GetWaitlistEntryAdminWaitlistEntryIdGetResponse = GetWaitlistEntryAdminWaitlistEntryIdGetResponses[keyof GetWaitlistEntryAdminWaitlistEntryIdGetResponses];

export type ApproveWaitlistEntryAdminWaitlistEntryIdApprovePostData = {
    body?: never;
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
    };
    query?: never;
    url: '/admin/waitlist/{entry_id}/approve';
};

export type ApproveWaitlistEntryAdminWaitlistEntryIdApprovePostErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Superadmin role required
     */
    403: unknown;
    /**
     * Entry not found
     */
    404: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type ApproveWaitlistEntryAdminWaitlistEntryIdApprovePostResponses = {
    /**
     * Successful Response
     */
    200: WaitlistEntryResponse;
};

export type ApproveWaitlistEntryAdminWaitlistEntryIdApprovePostResponse = ApproveWaitlistEntryAdminWaitlistEntryIdApprovePostResponses[keyof ApproveWaitlistEntryAdminWaitlistEntryIdApprovePostResponses];

export type ListWaitlistMessagesAdminWaitlistEntryIdMessagesGetData = {
    body?: never;
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
    };
    query?: never;
    url: '/admin/waitlist/{entry_id}/messages';
};

export type ListWaitlistMessagesAdminWaitlistEntryIdMessagesGetErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Superadmin role required
     */
    403: unknown;
    /**
     * Entry not found
     */
    404: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type ListWaitlistMessagesAdminWaitlistEntryIdMessagesGetResponses = {
    /**
     * Response List Waitlist Messages Admin Waitlist  Entry Id  Messages Get
     *
     * Successful Response
     */
    200: Array<WaitlistMessageResponse>;
};

export type ListWaitlistMessagesAdminWaitlistEntryIdMessagesGetResponse = ListWaitlistMessagesAdminWaitlistEntryIdMessagesGetResponses[keyof ListWaitlistMessagesAdminWaitlistEntryIdMessagesGetResponses];

export type SendWaitlistMessageAdminWaitlistEntryIdMessagesPostData = {
    body: WaitlistMessageRequest;
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
    };
    query?: never;
    url: '/admin/waitlist/{entry_id}/messages';
};

export type SendWaitlistMessageAdminWaitlistEntryIdMessagesPostErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Superadmin role required
     */
    403: unknown;
    /**
     * Entry not found
     */
    404: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type SendWaitlistMessageAdminWaitlistEntryIdMessagesPostResponses = {
    /**
     * Successful Response
     */
    201: WaitlistMessageResponse;
};

export type SendWaitlistMessageAdminWaitlistEntryIdMessagesPostResponse = SendWaitlistMessageAdminWaitlistEntryIdMessagesPostResponses[keyof SendWaitlistMessageAdminWaitlistEntryIdMessagesPostResponses];

export type RejectWaitlistEntryAdminWaitlistEntryIdRejectPostData = {
    body: WaitlistRejectRequest;
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
    };
    query?: never;
    url: '/admin/waitlist/{entry_id}/reject';
};

export type RejectWaitlistEntryAdminWaitlistEntryIdRejectPostErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Superadmin role required
     */
    403: unknown;
    /**
     * Entry not found
     */
    404: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type RejectWaitlistEntryAdminWaitlistEntryIdRejectPostResponses = {
    /**
     * Successful Response
     */
    200: WaitlistEntryResponse;
};

export type RejectWaitlistEntryAdminWaitlistEntryIdRejectPostResponse = RejectWaitlistEntryAdminWaitlistEntryIdRejectPostResponses[keyof RejectWaitlistEntryAdminWaitlistEntryIdRejectPostResponses];

export type ListAssignmentsAssignmentsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/assignments';
};

export type ListAssignmentsAssignmentsGetErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type ListAssignmentsAssignmentsGetResponses = {
    /**
     * Response List Assignments Assignments Get
     *
     * Successful Response
     */
    200: Array<AssignmentResponse>;
};

export type ListAssignmentsAssignmentsGetResponse = ListAssignmentsAssignmentsGetResponses[keyof ListAssignmentsAssignmentsGetResponses];

export type CreateAssignmentAssignmentsPostData = {
    body: AssignmentCreateRequest;
    path?: never;
    query?: never;
    url: '/assignments';
};

export type CreateAssignmentAssignmentsPostErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type CreateAssignmentAssignmentsPostResponses = {
    /**
     * Successful Response
     */
    201: AssignmentResponse;
};

export type CreateAssignmentAssignmentsPostResponse = CreateAssignmentAssignmentsPostResponses[keyof CreateAssignmentAssignmentsPostResponses];

export type GetAssignmentAssignmentsAssignmentIdGetData = {
    body?: never;
    path: {
        /**
         * Assignment Id
         */
        assignment_id: string;
    };
    query?: never;
    url: '/assignments/{assignment_id}';
};

export type GetAssignmentAssignmentsAssignmentIdGetErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Assignment not found
     */
    404: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type GetAssignmentAssignmentsAssignmentIdGetResponses = {
    /**
     * Successful Response
     */
    200: AssignmentResponse;
};

export type GetAssignmentAssignmentsAssignmentIdGetResponse = GetAssignmentAssignmentsAssignmentIdGetResponses[keyof GetAssignmentAssignmentsAssignmentIdGetResponses];

export type ListAcknowledgementsAssignmentsAssignmentIdAcknowledgementsGetData = {
    body?: never;
    path: {
        /**
         * Assignment Id
         */
        assignment_id: string;
    };
    query?: never;
    url: '/assignments/{assignment_id}/acknowledgements';
};

export type ListAcknowledgementsAssignmentsAssignmentIdAcknowledgementsGetErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Assignment not found
     */
    404: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type ListAcknowledgementsAssignmentsAssignmentIdAcknowledgementsGetResponses = {
    /**
     * Response List Acknowledgements Assignments  Assignment Id  Acknowledgements Get
     *
     * Successful Response
     */
    200: Array<AcknowledgementResponse>;
};

export type ListAcknowledgementsAssignmentsAssignmentIdAcknowledgementsGetResponse = ListAcknowledgementsAssignmentsAssignmentIdAcknowledgementsGetResponses[keyof ListAcknowledgementsAssignmentsAssignmentIdAcknowledgementsGetResponses];

export type AddFeedbackAssignmentsAssignmentIdFeedbackPostData = {
    body: AssignmentFeedbackRequest;
    path: {
        /**
         * Assignment Id
         */
        assignment_id: string;
    };
    query?: never;
    url: '/assignments/{assignment_id}/feedback';
};

export type AddFeedbackAssignmentsAssignmentIdFeedbackPostErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Assignment not found
     */
    404: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type AddFeedbackAssignmentsAssignmentIdFeedbackPostResponses = {
    /**
     * Successful Response
     */
    200: AssignmentResponse;
};

export type AddFeedbackAssignmentsAssignmentIdFeedbackPostResponse = AddFeedbackAssignmentsAssignmentIdFeedbackPostResponses[keyof AddFeedbackAssignmentsAssignmentIdFeedbackPostResponses];

export type ListConversationsConversationsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/conversations';
};

export type ListConversationsConversationsGetErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type ListConversationsConversationsGetResponses = {
    /**
     * Response List Conversations Conversations Get
     *
     * Successful Response
     */
    200: Array<ConversationResponse>;
};

export type ListConversationsConversationsGetResponse = ListConversationsConversationsGetResponses[keyof ListConversationsConversationsGetResponses];

export type CreateConversationConversationsPostData = {
    body: ConversationCreateRequest;
    path?: never;
    query?: never;
    url: '/conversations';
};

export type CreateConversationConversationsPostErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type CreateConversationConversationsPostResponses = {
    /**
     * Successful Response
     */
    201: ConversationResponse;
};

export type CreateConversationConversationsPostResponse = CreateConversationConversationsPostResponses[keyof CreateConversationConversationsPostResponses];

export type GetConversationConversationsConversationIdGetData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/conversations/{conversation_id}';
};

export type GetConversationConversationsConversationIdGetErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Conversation not found
     */
    404: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type GetConversationConversationsConversationIdGetResponses = {
    /**
     * Successful Response
     */
    200: ConversationResponse;
};

export type GetConversationConversationsConversationIdGetResponse = GetConversationConversationsConversationIdGetResponses[keyof GetConversationConversationsConversationIdGetResponses];

export type ListMessagesConversationsConversationIdMessagesGetData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/conversations/{conversation_id}/messages';
};

export type ListMessagesConversationsConversationIdMessagesGetErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Conversation not found
     */
    404: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type ListMessagesConversationsConversationIdMessagesGetResponses = {
    /**
     * Response List Messages Conversations  Conversation Id  Messages Get
     *
     * Successful Response
     */
    200: Array<MessageResponse>;
};

export type ListMessagesConversationsConversationIdMessagesGetResponse = ListMessagesConversationsConversationIdMessagesGetResponses[keyof ListMessagesConversationsConversationIdMessagesGetResponses];

export type SendMessageConversationsConversationIdMessagesPostData = {
    body: MessageCreateRequest;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/conversations/{conversation_id}/messages';
};

export type SendMessageConversationsConversationIdMessagesPostErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Conversation not found
     */
    404: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type SendMessageConversationsConversationIdMessagesPostResponses = {
    /**
     * Successful Response
     */
    201: MessageResponse;
};

export type SendMessageConversationsConversationIdMessagesPostResponse = SendMessageConversationsConversationIdMessagesPostResponses[keyof SendMessageConversationsConversationIdMessagesPostResponses];

export type MarkConversationReadConversationsConversationIdReadPostData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/conversations/{conversation_id}/read';
};

export type MarkConversationReadConversationsConversationIdReadPostErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type MarkConversationReadConversationsConversationIdReadPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type MarkConversationReadConversationsConversationIdReadPostResponse = MarkConversationReadConversationsConversationIdReadPostResponses[keyof MarkConversationReadConversationsConversationIdReadPostResponses];

export type ListDevicesDevicesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/devices';
};

export type ListDevicesDevicesGetErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type ListDevicesDevicesGetResponses = {
    /**
     * Response List Devices Devices Get
     *
     * Successful Response
     */
    200: Array<DeviceResponse>;
};

export type ListDevicesDevicesGetResponse = ListDevicesDevicesGetResponses[keyof ListDevicesDevicesGetResponses];

export type RegisterDeviceDevicesRegisterPostData = {
    body: DeviceRegisterRequest;
    path?: never;
    query?: never;
    url: '/devices/register';
};

export type RegisterDeviceDevicesRegisterPostErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
    /**
     * Rate limit exceeded
     */
    429: unknown;
};

export type RegisterDeviceDevicesRegisterPostResponses = {
    /**
     * Successful Response
     */
    201: DeviceResponse;
};

export type RegisterDeviceDevicesRegisterPostResponse = RegisterDeviceDevicesRegisterPostResponses[keyof RegisterDeviceDevicesRegisterPostResponses];

export type DeleteDeviceDevicesDeviceIdDeleteData = {
    body?: never;
    path: {
        /**
         * Device Id
         */
        device_id: string;
    };
    query?: never;
    url: '/devices/{device_id}';
};

export type DeleteDeviceDevicesDeviceIdDeleteErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Device not found
     */
    404: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type DeleteDeviceDevicesDeviceIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteDeviceDevicesDeviceIdDeleteResponse = DeleteDeviceDevicesDeviceIdDeleteResponses[keyof DeleteDeviceDevicesDeviceIdDeleteResponses];

export type ListEmployeesEmployeesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/employees';
};

export type ListEmployeesEmployeesGetErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Superadmin role required
     */
    403: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type ListEmployeesEmployeesGetResponses = {
    /**
     * Response List Employees Employees Get
     *
     * Successful Response
     */
    200: Array<EmployeeResponse>;
};

export type ListEmployeesEmployeesGetResponse = ListEmployeesEmployeesGetResponses[keyof ListEmployeesEmployeesGetResponses];

export type CreateEmployeeEmployeesPostData = {
    body: EmployeeCreateRequest;
    path?: never;
    query?: never;
    url: '/employees';
};

export type CreateEmployeeEmployeesPostErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Superadmin role required
     */
    403: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type CreateEmployeeEmployeesPostResponses = {
    /**
     * Successful Response
     */
    201: EmployeeResponse;
};

export type CreateEmployeeEmployeesPostResponse = CreateEmployeeEmployeesPostResponses[keyof CreateEmployeeEmployeesPostResponses];

export type DeleteEmployeeEmployeesEmployeeIdDeleteData = {
    body?: never;
    path: {
        /**
         * Employee Id
         */
        employee_id: string;
    };
    query?: never;
    url: '/employees/{employee_id}';
};

export type DeleteEmployeeEmployeesEmployeeIdDeleteErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Superadmin role required
     */
    403: unknown;
    /**
     * Employee not found
     */
    404: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type DeleteEmployeeEmployeesEmployeeIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteEmployeeEmployeesEmployeeIdDeleteResponse = DeleteEmployeeEmployeesEmployeeIdDeleteResponses[keyof DeleteEmployeeEmployeesEmployeeIdDeleteResponses];

export type GetEmployeeEmployeesEmployeeIdGetData = {
    body?: never;
    path: {
        /**
         * Employee Id
         */
        employee_id: string;
    };
    query?: never;
    url: '/employees/{employee_id}';
};

export type GetEmployeeEmployeesEmployeeIdGetErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Superadmin role required
     */
    403: unknown;
    /**
     * Employee not found
     */
    404: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type GetEmployeeEmployeesEmployeeIdGetResponses = {
    /**
     * Successful Response
     */
    200: EmployeeResponse;
};

export type GetEmployeeEmployeesEmployeeIdGetResponse = GetEmployeeEmployeesEmployeeIdGetResponses[keyof GetEmployeeEmployeesEmployeeIdGetResponses];

export type UpdateEmployeeEmployeesEmployeeIdPatchData = {
    body: EmployeeUpdateRequest;
    path: {
        /**
         * Employee Id
         */
        employee_id: string;
    };
    query?: never;
    url: '/employees/{employee_id}';
};

export type UpdateEmployeeEmployeesEmployeeIdPatchErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Superadmin role required
     */
    403: unknown;
    /**
     * Employee not found
     */
    404: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type UpdateEmployeeEmployeesEmployeeIdPatchResponses = {
    /**
     * Successful Response
     */
    200: EmployeeResponse;
};

export type UpdateEmployeeEmployeesEmployeeIdPatchResponse = UpdateEmployeeEmployeesEmployeeIdPatchResponses[keyof UpdateEmployeeEmployeesEmployeeIdPatchResponses];

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: HealthResponse;
};

export type HealthHealthGetResponse = HealthHealthGetResponses[keyof HealthHealthGetResponses];

export type RedeemInvitationEndpointInvitationsRedeemPostData = {
    body: InvitationRedeemRequest;
    path?: never;
    query?: never;
    url: '/invitations/redeem';
};

export type RedeemInvitationEndpointInvitationsRedeemPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RedeemInvitationEndpointInvitationsRedeemPostError = RedeemInvitationEndpointInvitationsRedeemPostErrors[keyof RedeemInvitationEndpointInvitationsRedeemPostErrors];

export type RedeemInvitationEndpointInvitationsRedeemPostResponses = {
    /**
     * Successful Response
     */
    200: InvitationRedeemResponse;
};

export type RedeemInvitationEndpointInvitationsRedeemPostResponse = RedeemInvitationEndpointInvitationsRedeemPostResponses[keyof RedeemInvitationEndpointInvitationsRedeemPostResponses];

export type ListCategoryPreferencesNotificationCategoryPreferencesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notification-category-preferences';
};

export type ListCategoryPreferencesNotificationCategoryPreferencesGetErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type ListCategoryPreferencesNotificationCategoryPreferencesGetResponses = {
    /**
     * Response List Category Preferences Notification Category Preferences Get
     *
     * Successful Response
     */
    200: Array<CategoryPreferenceResponse>;
};

export type ListCategoryPreferencesNotificationCategoryPreferencesGetResponse = ListCategoryPreferencesNotificationCategoryPreferencesGetResponses[keyof ListCategoryPreferencesNotificationCategoryPreferencesGetResponses];

export type UpsertCategoryPreferenceNotificationCategoryPreferencesPutData = {
    body: CategoryPreferenceUpsertRequest;
    path?: never;
    query?: never;
    url: '/notification-category-preferences';
};

export type UpsertCategoryPreferenceNotificationCategoryPreferencesPutErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type UpsertCategoryPreferenceNotificationCategoryPreferencesPutResponses = {
    /**
     * Successful Response
     */
    200: CategoryPreferenceResponse;
};

export type UpsertCategoryPreferenceNotificationCategoryPreferencesPutResponse = UpsertCategoryPreferenceNotificationCategoryPreferencesPutResponses[keyof UpsertCategoryPreferenceNotificationCategoryPreferencesPutResponses];

export type GetPreferencesNotificationPreferencesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notification-preferences';
};

export type GetPreferencesNotificationPreferencesGetErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type GetPreferencesNotificationPreferencesGetResponses = {
    /**
     * Successful Response
     */
    200: PreferencesResponse;
};

export type GetPreferencesNotificationPreferencesGetResponse = GetPreferencesNotificationPreferencesGetResponses[keyof GetPreferencesNotificationPreferencesGetResponses];

export type UpdatePreferencesNotificationPreferencesPatchData = {
    body: PreferencesUpdateRequest;
    path?: never;
    query?: never;
    url: '/notification-preferences';
};

export type UpdatePreferencesNotificationPreferencesPatchErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type UpdatePreferencesNotificationPreferencesPatchResponses = {
    /**
     * Successful Response
     */
    200: PreferencesResponse;
};

export type UpdatePreferencesNotificationPreferencesPatchResponse = UpdatePreferencesNotificationPreferencesPatchResponses[keyof UpdatePreferencesNotificationPreferencesPatchResponses];

export type ListTemplatesNotificationTemplatesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/notification-templates';
};

export type ListTemplatesNotificationTemplatesGetErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type ListTemplatesNotificationTemplatesGetResponses = {
    /**
     * Response List Templates Notification Templates Get
     *
     * Successful Response
     */
    200: Array<NotificationTemplateResponse>;
};

export type ListTemplatesNotificationTemplatesGetResponse = ListTemplatesNotificationTemplatesGetResponses[keyof ListTemplatesNotificationTemplatesGetResponses];

export type ListRecordingsRecordingsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/recordings';
};

export type ListRecordingsRecordingsGetErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type ListRecordingsRecordingsGetResponses = {
    /**
     * Response List Recordings Recordings Get
     *
     * Successful Response
     */
    200: Array<RecordingResponse>;
};

export type ListRecordingsRecordingsGetResponse = ListRecordingsRecordingsGetResponses[keyof ListRecordingsRecordingsGetResponses];

export type CreateRecordingRecordingsPostData = {
    body: RecordingCreateRequest;
    path?: never;
    query?: never;
    url: '/recordings';
};

export type CreateRecordingRecordingsPostErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type CreateRecordingRecordingsPostResponses = {
    /**
     * Successful Response
     */
    201: UploadUrlResponse;
};

export type CreateRecordingRecordingsPostResponse = CreateRecordingRecordingsPostResponses[keyof CreateRecordingRecordingsPostResponses];

export type GetRecordingRecordingsRecordingIdGetData = {
    body?: never;
    path: {
        /**
         * Recording Id
         */
        recording_id: string;
    };
    query?: never;
    url: '/recordings/{recording_id}';
};

export type GetRecordingRecordingsRecordingIdGetErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Recording not found
     */
    404: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type GetRecordingRecordingsRecordingIdGetResponses = {
    /**
     * Successful Response
     */
    200: RecordingResponse;
};

export type GetRecordingRecordingsRecordingIdGetResponse = GetRecordingRecordingsRecordingIdGetResponses[keyof GetRecordingRecordingsRecordingIdGetResponses];

export type ConfirmUploadRecordingsRecordingIdConfirmUploadPostData = {
    body: UploadConfirmRequest;
    path: {
        /**
         * Recording Id
         */
        recording_id: string;
    };
    query?: never;
    url: '/recordings/{recording_id}/confirm-upload';
};

export type ConfirmUploadRecordingsRecordingIdConfirmUploadPostErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Recording not found
     */
    404: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type ConfirmUploadRecordingsRecordingIdConfirmUploadPostResponses = {
    /**
     * Successful Response
     */
    200: RecordingResponse;
};

export type ConfirmUploadRecordingsRecordingIdConfirmUploadPostResponse = ConfirmUploadRecordingsRecordingIdConfirmUploadPostResponses[keyof ConfirmUploadRecordingsRecordingIdConfirmUploadPostResponses];

export type GetPlaybackUrlRecordingsRecordingIdPlaybackUrlGetData = {
    body?: never;
    path: {
        /**
         * Recording Id
         */
        recording_id: string;
    };
    query?: never;
    url: '/recordings/{recording_id}/playback-url';
};

export type GetPlaybackUrlRecordingsRecordingIdPlaybackUrlGetErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Not authorized to play this recording
     */
    403: unknown;
    /**
     * Recording not found
     */
    404: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type GetPlaybackUrlRecordingsRecordingIdPlaybackUrlGetResponses = {
    /**
     * Successful Response
     */
    200: PlaybackUrlResponse;
};

export type GetPlaybackUrlRecordingsRecordingIdPlaybackUrlGetResponse = GetPlaybackUrlRecordingsRecordingIdPlaybackUrlGetResponses[keyof GetPlaybackUrlRecordingsRecordingIdPlaybackUrlGetResponses];

export type ListResourcesResourcesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/resources';
};

export type ListResourcesResourcesGetErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type ListResourcesResourcesGetResponses = {
    /**
     * Response List Resources Resources Get
     *
     * Successful Response
     */
    200: Array<ResourceResponse>;
};

export type ListResourcesResourcesGetResponse = ListResourcesResourcesGetResponses[keyof ListResourcesResourcesGetResponses];

export type CreateResourceResourcesPostData = {
    body: ResourceCreateRequest;
    path?: never;
    query?: never;
    url: '/resources';
};

export type CreateResourceResourcesPostErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type CreateResourceResourcesPostResponses = {
    /**
     * Successful Response
     */
    201: ResourceResponse;
};

export type CreateResourceResourcesPostResponse = CreateResourceResourcesPostResponses[keyof CreateResourceResourcesPostResponses];

export type DeleteResourceResourcesResourceIdDeleteData = {
    body?: never;
    path: {
        /**
         * Resource Id
         */
        resource_id: string;
    };
    query?: never;
    url: '/resources/{resource_id}';
};

export type DeleteResourceResourcesResourceIdDeleteErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type DeleteResourceResourcesResourceIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteResourceResourcesResourceIdDeleteResponse = DeleteResourceResourcesResourceIdDeleteResponses[keyof DeleteResourceResourcesResourceIdDeleteResponses];

export type GetResourceResourcesResourceIdGetData = {
    body?: never;
    path: {
        /**
         * Resource Id
         */
        resource_id: string;
    };
    query?: never;
    url: '/resources/{resource_id}';
};

export type GetResourceResourcesResourceIdGetErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type GetResourceResourcesResourceIdGetResponses = {
    /**
     * Successful Response
     */
    200: ResourceResponse;
};

export type GetResourceResourcesResourceIdGetResponse = GetResourceResourcesResourceIdGetResponses[keyof GetResourceResourcesResourceIdGetResponses];

export type UpdateResourceResourcesResourceIdPatchData = {
    body: ResourceUpdateRequest;
    path: {
        /**
         * Resource Id
         */
        resource_id: string;
    };
    query?: never;
    url: '/resources/{resource_id}';
};

export type UpdateResourceResourcesResourceIdPatchErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Resource not found
     */
    404: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type UpdateResourceResourcesResourceIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ResourceResponse;
};

export type UpdateResourceResourcesResourceIdPatchResponse = UpdateResourceResourcesResourceIdPatchResponses[keyof UpdateResourceResourcesResourceIdPatchResponses];

export type ListSettingsSettingsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/settings';
};

export type ListSettingsSettingsGetErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Superadmin role required
     */
    403: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type ListSettingsSettingsGetResponses = {
    /**
     * Response List Settings Settings Get
     *
     * Successful Response
     */
    200: Array<SettingResponse>;
};

export type ListSettingsSettingsGetResponse = ListSettingsSettingsGetResponses[keyof ListSettingsSettingsGetResponses];

export type CreateSettingSettingsPostData = {
    body: SettingCreateRequest;
    path?: never;
    query?: never;
    url: '/settings';
};

export type CreateSettingSettingsPostErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Superadmin role required
     */
    403: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type CreateSettingSettingsPostResponses = {
    /**
     * Successful Response
     */
    201: SettingResponse;
};

export type CreateSettingSettingsPostResponse = CreateSettingSettingsPostResponses[keyof CreateSettingSettingsPostResponses];

export type ListActivityLogsSettingsActivityLogsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/settings/activity-logs/';
};

export type ListActivityLogsSettingsActivityLogsGetErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Superadmin role required
     */
    403: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type ListActivityLogsSettingsActivityLogsGetResponses = {
    /**
     * Response List Activity Logs Settings Activity Logs  Get
     *
     * Successful Response
     */
    200: Array<ActivityLogResponse>;
};

export type ListActivityLogsSettingsActivityLogsGetResponse = ListActivityLogsSettingsActivityLogsGetResponses[keyof ListActivityLogsSettingsActivityLogsGetResponses];

export type GetSettingSettingsKeyGetData = {
    body?: never;
    path: {
        /**
         * Key
         */
        key: string;
    };
    query?: never;
    url: '/settings/{key}';
};

export type GetSettingSettingsKeyGetErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Superadmin role required
     */
    403: unknown;
    /**
     * Setting not found
     */
    404: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type GetSettingSettingsKeyGetResponses = {
    /**
     * Successful Response
     */
    200: SettingResponse;
};

export type GetSettingSettingsKeyGetResponse = GetSettingSettingsKeyGetResponses[keyof GetSettingSettingsKeyGetResponses];

export type UpdateSettingSettingsKeyPutData = {
    body: SettingUpdateRequest;
    path: {
        /**
         * Key
         */
        key: string;
    };
    query?: never;
    url: '/settings/{key}';
};

export type UpdateSettingSettingsKeyPutErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Superadmin role required
     */
    403: unknown;
    /**
     * Setting not found
     */
    404: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type UpdateSettingSettingsKeyPutResponses = {
    /**
     * Successful Response
     */
    200: SettingResponse;
};

export type UpdateSettingSettingsKeyPutResponse = UpdateSettingSettingsKeyPutResponses[keyof UpdateSettingSettingsKeyPutResponses];

export type ListStudiosStudiosGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/studios';
};

export type ListStudiosStudiosGetErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type ListStudiosStudiosGetResponses = {
    /**
     * Response List Studios Studios Get
     *
     * Successful Response
     */
    200: Array<StudioResponse>;
};

export type ListStudiosStudiosGetResponse = ListStudiosStudiosGetResponses[keyof ListStudiosStudiosGetResponses];

export type CreateStudioStudiosPostData = {
    body: StudioCreateRequest;
    path?: never;
    query?: never;
    url: '/studios';
};

export type CreateStudioStudiosPostErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type CreateStudioStudiosPostResponses = {
    /**
     * Successful Response
     */
    201: StudioResponse;
};

export type CreateStudioStudiosPostResponse = CreateStudioStudiosPostResponses[keyof CreateStudioStudiosPostResponses];

export type GetStudioStudiosStudioIdGetData = {
    body?: never;
    path: {
        /**
         * Studio Id
         */
        studio_id: string;
    };
    query?: never;
    url: '/studios/{studio_id}';
};

export type GetStudioStudiosStudioIdGetErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Studio not found
     */
    404: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type GetStudioStudiosStudioIdGetResponses = {
    /**
     * Successful Response
     */
    200: StudioResponse;
};

export type GetStudioStudiosStudioIdGetResponse = GetStudioStudiosStudioIdGetResponses[keyof GetStudioStudiosStudioIdGetResponses];

export type UpdateStudioStudiosStudioIdPatchData = {
    body: StudioUpdateRequest;
    path: {
        /**
         * Studio Id
         */
        studio_id: string;
    };
    query?: never;
    url: '/studios/{studio_id}';
};

export type UpdateStudioStudiosStudioIdPatchErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Studio not found
     */
    404: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type UpdateStudioStudiosStudioIdPatchResponses = {
    /**
     * Successful Response
     */
    200: StudioResponse;
};

export type UpdateStudioStudiosStudioIdPatchResponse = UpdateStudioStudiosStudioIdPatchResponses[keyof UpdateStudioStudiosStudioIdPatchResponses];

export type ListInvitationsStudiosStudioIdInvitationsGetData = {
    body?: never;
    path: {
        /**
         * Studio Id
         */
        studio_id: string;
    };
    query?: {
        /**
         * Status
         */
        status?: 'pending' | 'accepted' | 'declined' | 'expired' | 'revoked' | null;
    };
    url: '/studios/{studio_id}/invitations';
};

export type ListInvitationsStudiosStudioIdInvitationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListInvitationsStudiosStudioIdInvitationsGetError = ListInvitationsStudiosStudioIdInvitationsGetErrors[keyof ListInvitationsStudiosStudioIdInvitationsGetErrors];

export type ListInvitationsStudiosStudioIdInvitationsGetResponses = {
    /**
     * Response List Invitations Studios  Studio Id  Invitations Get
     *
     * Successful Response
     */
    200: Array<InvitationResponse>;
};

export type ListInvitationsStudiosStudioIdInvitationsGetResponse = ListInvitationsStudiosStudioIdInvitationsGetResponses[keyof ListInvitationsStudiosStudioIdInvitationsGetResponses];

export type CreateStudioInvitationStudiosStudioIdInvitationsPostData = {
    body: InvitationCreateRequest;
    path: {
        /**
         * Studio Id
         */
        studio_id: string;
    };
    query?: never;
    url: '/studios/{studio_id}/invitations';
};

export type CreateStudioInvitationStudiosStudioIdInvitationsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateStudioInvitationStudiosStudioIdInvitationsPostError = CreateStudioInvitationStudiosStudioIdInvitationsPostErrors[keyof CreateStudioInvitationStudiosStudioIdInvitationsPostErrors];

export type CreateStudioInvitationStudiosStudioIdInvitationsPostResponses = {
    /**
     * Successful Response
     */
    201: InvitationResponse;
};

export type CreateStudioInvitationStudiosStudioIdInvitationsPostResponse = CreateStudioInvitationStudiosStudioIdInvitationsPostResponses[keyof CreateStudioInvitationStudiosStudioIdInvitationsPostResponses];

export type CreateBatchInvitationStudiosStudioIdInvitationsBatchPostData = {
    body: InvitationBatchCreateRequest;
    path: {
        /**
         * Studio Id
         */
        studio_id: string;
    };
    query?: never;
    url: '/studios/{studio_id}/invitations/batch';
};

export type CreateBatchInvitationStudiosStudioIdInvitationsBatchPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateBatchInvitationStudiosStudioIdInvitationsBatchPostError = CreateBatchInvitationStudiosStudioIdInvitationsBatchPostErrors[keyof CreateBatchInvitationStudiosStudioIdInvitationsBatchPostErrors];

export type CreateBatchInvitationStudiosStudioIdInvitationsBatchPostResponses = {
    /**
     * Successful Response
     */
    201: InvitationResponse;
};

export type CreateBatchInvitationStudiosStudioIdInvitationsBatchPostResponse = CreateBatchInvitationStudiosStudioIdInvitationsBatchPostResponses[keyof CreateBatchInvitationStudiosStudioIdInvitationsBatchPostResponses];

export type RegenerateInvitationTokenStudiosStudioIdInvitationsInvitationIdRegeneratePostData = {
    body?: never;
    path: {
        /**
         * Studio Id
         */
        studio_id: string;
        /**
         * Invitation Id
         */
        invitation_id: string;
    };
    query?: never;
    url: '/studios/{studio_id}/invitations/{invitation_id}/regenerate';
};

export type RegenerateInvitationTokenStudiosStudioIdInvitationsInvitationIdRegeneratePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegenerateInvitationTokenStudiosStudioIdInvitationsInvitationIdRegeneratePostError = RegenerateInvitationTokenStudiosStudioIdInvitationsInvitationIdRegeneratePostErrors[keyof RegenerateInvitationTokenStudiosStudioIdInvitationsInvitationIdRegeneratePostErrors];

export type RegenerateInvitationTokenStudiosStudioIdInvitationsInvitationIdRegeneratePostResponses = {
    /**
     * Successful Response
     */
    200: InvitationResponse;
};

export type RegenerateInvitationTokenStudiosStudioIdInvitationsInvitationIdRegeneratePostResponse = RegenerateInvitationTokenStudiosStudioIdInvitationsInvitationIdRegeneratePostResponses[keyof RegenerateInvitationTokenStudiosStudioIdInvitationsInvitationIdRegeneratePostResponses];

export type ListLoansStudiosStudioIdLoansGetData = {
    body?: never;
    path: {
        /**
         * Studio Id
         */
        studio_id: string;
    };
    query?: {
        /**
         * Student User Id
         *
         * Filter by student
         */
        student_user_id?: string | null;
    };
    url: '/studios/{studio_id}/loans';
};

export type ListLoansStudiosStudioIdLoansGetErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type ListLoansStudiosStudioIdLoansGetResponses = {
    /**
     * Response List Loans Studios  Studio Id  Loans Get
     *
     * Successful Response
     */
    200: Array<LoanResponse>;
};

export type ListLoansStudiosStudioIdLoansGetResponse = ListLoansStudiosStudioIdLoansGetResponses[keyof ListLoansStudiosStudioIdLoansGetResponses];

export type CreateLoanStudiosStudioIdLoansPostData = {
    body: LoanCreateRequest;
    path: {
        /**
         * Studio Id
         */
        studio_id: string;
    };
    query?: never;
    url: '/studios/{studio_id}/loans';
};

export type CreateLoanStudiosStudioIdLoansPostErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type CreateLoanStudiosStudioIdLoansPostResponses = {
    /**
     * Successful Response
     */
    201: LoanResponse;
};

export type CreateLoanStudiosStudioIdLoansPostResponse = CreateLoanStudiosStudioIdLoansPostResponses[keyof CreateLoanStudiosStudioIdLoansPostResponses];

export type DeleteLoanStudiosStudioIdLoansLoanIdDeleteData = {
    body?: never;
    path: {
        /**
         * Studio Id
         */
        studio_id: string;
        /**
         * Loan Id
         */
        loan_id: string;
    };
    query?: never;
    url: '/studios/{studio_id}/loans/{loan_id}';
};

export type DeleteLoanStudiosStudioIdLoansLoanIdDeleteErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Loan not found
     */
    404: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type DeleteLoanStudiosStudioIdLoansLoanIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteLoanStudiosStudioIdLoansLoanIdDeleteResponse = DeleteLoanStudiosStudioIdLoansLoanIdDeleteResponses[keyof DeleteLoanStudiosStudioIdLoansLoanIdDeleteResponses];

export type GetLoanStudiosStudioIdLoansLoanIdGetData = {
    body?: never;
    path: {
        /**
         * Studio Id
         */
        studio_id: string;
        /**
         * Loan Id
         */
        loan_id: string;
    };
    query?: never;
    url: '/studios/{studio_id}/loans/{loan_id}';
};

export type GetLoanStudiosStudioIdLoansLoanIdGetErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Loan not found
     */
    404: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type GetLoanStudiosStudioIdLoansLoanIdGetResponses = {
    /**
     * Successful Response
     */
    200: LoanResponse;
};

export type GetLoanStudiosStudioIdLoansLoanIdGetResponse = GetLoanStudiosStudioIdLoansLoanIdGetResponses[keyof GetLoanStudiosStudioIdLoansLoanIdGetResponses];

export type UpdateLoanStudiosStudioIdLoansLoanIdPatchData = {
    body: LoanUpdateRequest;
    path: {
        /**
         * Studio Id
         */
        studio_id: string;
        /**
         * Loan Id
         */
        loan_id: string;
    };
    query?: never;
    url: '/studios/{studio_id}/loans/{loan_id}';
};

export type UpdateLoanStudiosStudioIdLoansLoanIdPatchErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Loan not found
     */
    404: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type UpdateLoanStudiosStudioIdLoansLoanIdPatchResponses = {
    /**
     * Successful Response
     */
    200: LoanResponse;
};

export type UpdateLoanStudiosStudioIdLoansLoanIdPatchResponse = UpdateLoanStudiosStudioIdLoansLoanIdPatchResponses[keyof UpdateLoanStudiosStudioIdLoansLoanIdPatchResponses];

export type UpdateParentChildPermissionsStudiosStudioIdParentChildrenPcIdPatchData = {
    body: ParentChildPermissionUpdate;
    path: {
        /**
         * Studio Id
         */
        studio_id: string;
        /**
         * Pc Id
         */
        pc_id: string;
    };
    query?: never;
    url: '/studios/{studio_id}/parent-children/{pc_id}';
};

export type UpdateParentChildPermissionsStudiosStudioIdParentChildrenPcIdPatchErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Not found
     */
    404: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type UpdateParentChildPermissionsStudiosStudioIdParentChildrenPcIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ParentChildPermissions;
};

export type UpdateParentChildPermissionsStudiosStudioIdParentChildrenPcIdPatchResponse = UpdateParentChildPermissionsStudiosStudioIdParentChildrenPcIdPatchResponses[keyof UpdateParentChildPermissionsStudiosStudioIdParentChildrenPcIdPatchResponses];

export type ListStudentsStudiosStudioIdStudentsGetData = {
    body?: never;
    path: {
        /**
         * Studio Id
         */
        studio_id: string;
    };
    query?: {
        /**
         * Search
         *
         * Search by email
         */
        search?: string | null;
    };
    url: '/studios/{studio_id}/students';
};

export type ListStudentsStudiosStudioIdStudentsGetErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type ListStudentsStudiosStudioIdStudentsGetResponses = {
    /**
     * Response List Students Studios  Studio Id  Students Get
     *
     * Successful Response
     */
    200: Array<StudentListItem>;
};

export type ListStudentsStudiosStudioIdStudentsGetResponse = ListStudentsStudiosStudioIdStudentsGetResponses[keyof ListStudentsStudiosStudioIdStudentsGetResponses];

export type GetStudentDetailStudiosStudioIdStudentsStudentUserIdGetData = {
    body?: never;
    path: {
        /**
         * Studio Id
         */
        studio_id: string;
        /**
         * Student User Id
         */
        student_user_id: string;
    };
    query?: never;
    url: '/studios/{studio_id}/students/{student_user_id}';
};

export type GetStudentDetailStudiosStudioIdStudentsStudentUserIdGetErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Student not found
     */
    404: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type GetStudentDetailStudiosStudioIdStudentsStudentUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: StudentDetail;
};

export type GetStudentDetailStudiosStudioIdStudentsStudentUserIdGetResponse = GetStudentDetailStudiosStudioIdStudentsStudentUserIdGetResponses[keyof GetStudentDetailStudiosStudioIdStudentsStudentUserIdGetResponses];

export type SuspendStudioStudiosStudioIdSuspendPostData = {
    body?: never;
    path: {
        /**
         * Studio Id
         */
        studio_id: string;
    };
    query?: never;
    url: '/studios/{studio_id}/suspend';
};

export type SuspendStudioStudiosStudioIdSuspendPostErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Studio not found
     */
    404: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type SuspendStudioStudiosStudioIdSuspendPostResponses = {
    /**
     * Successful Response
     */
    200: StudioResponse;
};

export type SuspendStudioStudiosStudioIdSuspendPostResponse = SuspendStudioStudiosStudioIdSuspendPostResponses[keyof SuspendStudioStudiosStudioIdSuspendPostResponses];

export type VerifyStudioStudiosStudioIdVerifyPostData = {
    body?: never;
    path: {
        /**
         * Studio Id
         */
        studio_id: string;
    };
    query?: never;
    url: '/studios/{studio_id}/verify';
};

export type VerifyStudioStudiosStudioIdVerifyPostErrors = {
    /**
     * Bad request — invalid input
     */
    400: unknown;
    /**
     * Not authenticated
     */
    401: unknown;
    /**
     * Studio not found
     */
    404: unknown;
    /**
     * Method not allowed
     */
    405: unknown;
    /**
     * Validation error
     */
    422: unknown;
};

export type VerifyStudioStudiosStudioIdVerifyPostResponses = {
    /**
     * Successful Response
     */
    200: StudioResponse;
};

export type VerifyStudioStudiosStudioIdVerifyPostResponse = VerifyStudioStudiosStudioIdVerifyPostResponses[keyof VerifyStudioStudiosStudioIdVerifyPostResponses];

export type SubmitWaitlistWaitlistPostData = {
    body: WaitlistSubmitRequest;
    path?: never;
    query?: never;
    url: '/waitlist';
};

export type SubmitWaitlistWaitlistPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubmitWaitlistWaitlistPostError = SubmitWaitlistWaitlistPostErrors[keyof SubmitWaitlistWaitlistPostErrors];

export type SubmitWaitlistWaitlistPostResponses = {
    /**
     * Successful Response
     */
    201: WaitlistEntryResponse;
};

export type SubmitWaitlistWaitlistPostResponse = SubmitWaitlistWaitlistPostResponses[keyof SubmitWaitlistWaitlistPostResponses];
